version: '3.9'
services:
  node:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
      - "logs:/app/dist/logs/"
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks: 
      - user-defined
    environment:
      PORT: ${PORT}
    restart: on-failure:10 
  postrges:
    build: ./postgres/
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks: 
      - user-defined
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure:10 

networks:
  user-defined:
    driver: bridge

volumes:
  dbdata:
  logs: